# Generated by Django 3.1.3 on 2020-11-18 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('merchan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Merchandise',
        ),
    ]
