# Generated by Django 3.1.3 on 2020-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0003_auto_20201121_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='about_preset',
            field=models.TextField(default=0, max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchandise',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
