# Generated by Django 3.1.3 on 2020-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0004_auto_20201122_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='about_preset',
            field=models.TextField(default='', max_length=2048),
        ),
    ]
