# Generated by Django 3.1.3 on 2020-11-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0008_auto_20201124_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='merchandise',
            name='width_field',
        ),
    ]
