# Generated by Django 3.1.3 on 2020-12-01 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0013_auto_20201201_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='likes',
        ),
    ]
