# Generated by Django 3.1.3 on 2020-12-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0016_auto_20201202_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
    ]
