# Generated by Django 3.1.3 on 2020-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0018_auto_20201202_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='before_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
