# Generated by Django 3.1.3 on 2020-12-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0019_auto_20201202_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchandise',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='after_img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='before_img',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/', width_field='width_field'),
        ),
    ]
