# Generated by Django 3.1.3 on 2020-12-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0020_auto_20201202_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
