# Generated by Django 3.1.3 on 2020-12-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0021_merchandise_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
