# Generated by Django 3.1.3 on 2020-12-08 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchan', '0023_auto_20201208_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
