# Generated by Django 3.1.3 on 2020-12-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0026_auto_20201209_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='after_img',
            field=models.ImageField(blank=True, height_field='height_field2', null=True, upload_to='images/', width_field='width_field2'),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='before_img',
            field=models.ImageField(blank=True, height_field='height_field1', null=True, upload_to='images/', width_field='width_field1'),
        ),
    ]
