# Generated by Django 3.1.3 on 2020-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0029_auto_20201209_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='height_field1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='height_field2',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='width_field1',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='width_field2',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
