# Generated by Django 3.1.3 on 2020-12-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchan', '0030_auto_20201209_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='height_field1',
            field=models.IntegerField(default=2048, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='height_field2',
            field=models.IntegerField(default=2048, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='width_field1',
            field=models.IntegerField(default=1536, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='width_field2',
            field=models.IntegerField(default=1536, null=True),
        ),
    ]
