# Generated by Django 3.1.3 on 2020-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201123_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='product',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
