# Generated by Django 3.1.3 on 2020-11-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201125_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
