# Generated by Django 3.1.3 on 2020-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201209_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
